import React from 'react';
import Head from 'next/head';
import { HiOutlineMail, HiOutlinePhoneOutgoing } from 'react-icons/hi';
import { MdOutlineLocationOn } from 'react-icons/md';
import { doc, setDoc } from 'firebase/firestore';
import toast, { Toaster } from 'react-hot-toast';

import MainNavbar from 'src/components/Navbar';
import TextField from 'src/components/TextField';
import DefaultButton from 'src/components/Buttons';
import Footer from 'src/components/Footer';
import { db } from 'src/firebase/clientApp';

export default function Contact() {
  const [name, setName] = React.useState('');
  const [email, setEmail] = React.useState('');
  const [phone, setPhone] = React.useState('');
  const [address, setAddress] = React.useState('');
  const [subject, setSubject] = React.useState('');
  const [message, setMessage] = React.useState('');

  const data = {
    name: name,
    email: email,
    phone: phone,
    address: address,
    subject: subject,
    message: message,
  };

  const handleSubmit = async (e) => {
    const toastId = toast.loading('Sending...', { duration: Infinity });
    e.preventDefault();
    const contactRef = doc(db, `contacts/${name}`);
    await setDoc(contactRef, data, { merge: true })
      .then(() => {
        toast.dismiss(toastId);
        toast.success('Message sent!');
      })
      .catch((err) => {
        toast.error(err.message);
      });
    setName('');
    setEmail('');
    setPhone('');
    setAddress('');
    setSubject('');
    setMessage('');
  };

  return (
    <div>
      <Head>
        <title>Energy For The Future</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="h-screen">
          <MainNavbar />
          <div className="container mx-auto pt-16">
            <div className="lg:flex">
              <div className="xl:w-2/5 lg:w-2/5 bg-emerald-600 py-20 xl:rounded-bl rounded-tl rounded-md xl:rounded-md-none">
                <div className="xl:w-5/6 xl:px-0 px-8 mx-auto">
                  <h1 className="xl:text-4xl text-3xl pb-4 text-white font-bold">
                    Get in touch
                  </h1>
                  <p className="text-xl text-white pb-8 leading-relaxed font-normal lg:pr-4">
                    {/* Got a question about us? Are you interested in partnering
                    with us? Have some suggestions or just want to say Hi? Just
                    contact us. We are here to asset you. */}
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Aliquam in magna vel eros gravida sagittis. Nulla bibendum
                    enim at dui lacinia, eu vestibulum tellus cursus. Aenean
                    vitae justo eros. Nam elementum nisi quis est tempor tempor.
                    Nullam sed justo nec ligula sollicitudin malesuada vel vel
                    orci.
                  </p>
                  <div className="flex pb-4 items-center">
                    <div>
                      <HiOutlinePhoneOutgoing className="h-5 w-5 text-white" />
                    </div>
                    <p className="pl-4 text-white text-base">
                      +1 (303) 954 0463
                    </p>
                  </div>
                  <div className="flex items-center">
                    <div>
                      <HiOutlineMail className="h-5 w-5 text-white" />
                    </div>
                    <p className="pl-4 text-white text-base">
                      sales@soprissolar.com
                    </p>
                  </div>
                  <p className="text-lg flex items-center text-white pt-10 mt-5 tracking-wide">
                    <MdOutlineLocationOn className="h-10 w-10 mr-4" />
                    5609 W 6th Ave Frontage Rd N STE B, <br /> Lakewood,
                    Colorado, United States
                  </p>
                </div>
              </div>
              <div className="xl:w-3/5 lg:w-3/5 h-full pt-5 pb-5 xl:pr-5 xl:pl-0 rounded-tr rounded-br">
                <form
                  id="contact"
                  className="py-4 px-8 rounded-tr rounded-br"
                  onSubmit={handleSubmit}
                >
                  <h1 className="text-4xl text-gray-800 dark:text-gray-200 font-bold mb-6">
                    Enter Details
                  </h1>
                  <div className="block xl:flex w-full flex-wrap justify-between mb-6">
                    <div className="p-2 w-full xl:w-1/2">
                      <label htmlFor="name" className="sr-only">
                        Name
                      </label>
                      <TextField
                        id="name"
                        value={name}
                        name="name"
                        autoComplete="name"
                        required
                        placeholder="Name"
                        onChange={(e) => setName(e.target.value)}
                      />
                    </div>
                    <div className="p-2 w-full xl:w-1/2">
                      <label htmlFor="email" className="sr-only">
                        Email
                      </label>
                      <TextField
                        id="email"
                        value={email}
                        name="email"
                        type="email"
                        autoComplete="email"
                        required
                        placeholder="Email"
                        onChange={(e) => setEmail(e.target.value)}
                      />
                    </div>
                    <div className="p-2 w-full xl:w-1/2">
                      <label htmlFor="phone" className="sr-only">
                        Name
                      </label>
                      <TextField
                        id="phone"
                        value={phone}
                        name="phone"
                        type="tel"
                        autoComplete="tel"
                        placeholder="Phone eg. +1 (123) 456-789"
                        onChange={(e) => setPhone(e.target.value)}
                      />
                    </div>
                    <div className="p-2 w-full xl:w-1/2">
                      <label htmlFor="address" className="sr-only">
                        Address
                      </label>
                      <TextField
                        id="address"
                        value={address}
                        name="address"
                        type="text"
                        autoComplete="street-address"
                        placeholder="Address"
                        onChange={(e) => setAddress(e.target.value)}
                      />
                    </div>
                    <div className="p-2 w-full">
                      <label htmlFor="email" className="sr-only">
                        Subject
                      </label>
                      <TextField
                        id="subject"
                        value={subject}
                        name="subject"
                        type="text"
                        placeholder="Subject"
                        onChange={(e) => setSubject(e.target.value)}
                      />
                    </div>
                    <div className="p-2 w-full">
                      <label htmlFor="message" className="sr-only">
                        Message
                      </label>
                      <textarea
                        maxLength="500"
                        value={message}
                        rows="4"
                        type="text"
                        id="subject"
                        name="subject"
                        className="form-input appearance-none md:text-md dark:bg-slate-800 dark:border-slate-800 h-32 mt-3 rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 dark:placeholder-slate-400 text-gray-900 dark:text-slate-200 focus:outline-none focus:ring-orange-400 focus:ring-2  focus:z-10 text-sm"
                        placeholder="Message"
                        required
                        onChange={(e) => setMessage(e.target.value)}
                      />
                    </div>
                    <div className="px-2 mt-3 w-40">
                      <DefaultButton type="submit">Submit</DefaultButton>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <Toaster
            position="top-center"
            toastOptions={{
              // Define default options
              duration: 5000,
              style: {
                background: '#363636',
                color: '#fff',
              },
            }}
          />
          <Footer />
        </section>
      </main>
    </div>
  );
}
