import * as React from 'react';
import { useState } from 'react';
import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import { useRouter } from 'next/router';
import Link from 'next/link';

import MainNavbar from 'src/components/Navbar';
import GoogleLogo from 'src/components/Assets/Logos/GoogleLogo';
import TwitterLogo from 'src/components/Assets/Logos/TwitterLogo';
import { UserAuth } from 'src/firebase/Context/auth.context';
import {
  signInWithEmailPassword,
  signInWithGoogle,
  signInWithTwitter,
} from 'src/firebase/Context/authOptions';
import Loading from 'src/components/Loading';

export default function LoginPage() {
  const { user, loading } = UserAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();

  const LoginWithGoogle = () => {
    signInWithGoogle();
  };

  const LoginWithTwitter = () => {
    signInWithTwitter();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await signInWithEmailPassword(email, password);
      router.push('/');
    } catch (err) {
      console.log(err.code);
      if (err.code.includes('email')) {
        setEmail('');
      } else {
        setPassword('');
      }
    }
  };

  if (loading) {
    return <Loading />;
  }

  if (user) {
    router.push('/');
  }

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-login-bg h-[100vh] w-[100vw] bg-center bg-cover">
        <MainNavbar />
        <main>
          <div className="h-full w-full py-10 px-4">
            <div className="flex flex-col items-center justify-center">
              <div className="bg-white dark:bg-slate-900 bg-opacity-90 filter backdrop-blur-md shadow rounded-xl md:w-2/4 lg:w-2/5 xl:2/5 2xl:w-1/4 w-full py-10 px-14 mt-16">
                {' '}
                <p
                  tabIndex="0"
                  className="focus:outline-none text-2xl font-extrabold leading-6 text-center text-slate-800 dark:text-white"
                >
                  Login to your account
                </p>
                <button
                  aria-label="Continue with google"
                  onClick={LoginWithGoogle}
                  role="button"
                  className="group py-3.5 px-4 border-2 bg-slate-100 dark:bg-slate-800 rounded-full border-gray-600 hover:border-orange-400 flex justify-center items-center w-full mt-8 transition duration-200"
                >
                  <GoogleLogo />
                  <p className="group text-base font-semibold ml-4 text-slate-800 dark:text-white group-hover:text-orange-500 dark:group-hover:text-orange-400">
                    Continue with Google
                  </p>
                </button>
                <button
                  aria-label="Continue with twitter"
                  onClick={LoginWithTwitter}
                  role="button"
                  className="group py-3.5 px-4 border-2 bg-slate-100 dark:bg-slate-800 rounded-full border-gray-600 hover:border-orange-400 flex justify-center items-center w-full mt-4 transition duration-200"
                >
                  <TwitterLogo />
                  <p className="text-base font-semibold ml-4 text-slate-800 dark:text-white group-hover:text-orange-500 dark:group-hover:text-orange-400">
                    Continue with Twitter
                  </p>
                </button>
                <div className="relative flex py-5 items-center">
                  <div className="flex-grow border-t border-slate-700 dark:border-slate-300"></div>
                  <span className="flex-shrink mx-4 text-slate-700 dark:text-slate-300">
                    OR
                  </span>
                  <div className="flex-grow border-t border-slate-700 dark:border-slate-300"></div>
                </div>
                <form onSubmit={handleSubmit}>
                  <div>
                    <label htmlFor="email" className="sr-only">
                      Email
                    </label>
                    <input
                      id="email"
                      name="email"
                      type="email"
                      autoComplete="email"
                      value={email}
                      autoFocus
                      required
                      className="appearance-none md:text-md dark:bg-slate-800 dark:border-slate-800 h-14 mt-3 rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 dark:placeholder-slate-400 text-gray-900 dark:text-slate-200 focus:outline-none focus:ring-orange-400 focus:ring-2  focus:z-10 text-sm"
                      placeholder="Email"
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div>
                    <label htmlFor="password" className="sr-only">
                      Password
                    </label>
                    <input
                      id="password"
                      name="password"
                      type="password"
                      autoComplete="current-password"
                      required
                      value={password}
                      className="appearance-none md:text-md dark:bg-slate-800 dark:border-slate-800  h-14 mt-3 rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 dark:placeholder-slate-400 text-gray-900 dark:text-slate-200 focus:outline-none focus:ring-orange-400 focus:ring-2  focus:z-10 text-sm"
                      placeholder="Password"
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                  <div className="mt-8">
                    <button
                      role="button"
                      className="text-md font-semibold leading-none text-white dark:text-black drop-shadow-md shadow-orange-400 bg-gray-800 dark:bg-gray-200 hover:bg-gray-700 dark:hover:bg-gray-400 border-none rounded-md py-4 w-full transition duration-500"
                    >
                      Log In
                    </button>
                  </div>
                  <p
                    tabIndex="0"
                    className="focus:outline-none text-sm mt-4 font-medium leading-none text-center text-gray-500 dark:text-gray-300"
                  >
                    Don&apos;t have account?
                    <Link href="/register">
                      <a
                        rel="noopener"
                        className="hover:text-gray-500 focus:text-gray-500 focus:outline-none focus:underline hover:underline text-sm font-medium leading-none text-gray-800 dark:text-gray-100 cursor-pointer"
                      >
                        {' '}
                        Sign up here
                      </a>
                    </Link>
                  </p>
                </form>
              </div>
              <Toaster
                position="top-center"
                toastOptions={{
                  // Define default options
                  duration: 5000,
                  style: {
                    background: '#363636',
                    color: '#fff',
                  },
                }}
              />
            </div>
          </div>
        </main>
      </div>
    </React.Fragment>
  );
}
