import * as React from 'react';
import { useState } from 'react';
import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import { useRouter } from 'next/router';
import Link from 'next/link';

import MainNavbar from 'src/components/Navbar';
import { UserAuth } from 'src/firebase/Context/auth.context';
import { createUserwithEmailPassword } from 'src/firebase/Context/authOptions';
import Loading from 'src/components/Loading';
import TextField from 'src/components/TextField';
import DefaultButton from 'src/components/Buttons';

export default function LoginPage() {
  const { user, loading } = UserAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const router = useRouter();

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await createUserwithEmailPassword(email, password);
      // router.push('/');
    } catch (err) {
      console.log(err.code);
      if (err.code.includes('email')) {
        setEmail('');
      } else {
        setPassword('');
      }
    }
  };

  if (loading) {
    return <Loading />;
  }

  if (user) {
    router.push('/');
  }

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-signup-bg h-[100vh] w-[100vw] bg-center bg-cover">
        <MainNavbar />
        <main>
          <div className="h-full w-full py-10 px-4">
            <div className="flex flex-col items-center justify-center">
              <div className="bg-white dark:bg-slate-900 bg-opacity-90 filter backdrop-blur-md shadow rounded-xl md:w-2/4 lg:w-2/5 xl:2/5 2xl:w-1/4 w-full py-10 px-14 mt-16">
                <p
                  tabIndex="0"
                  className="focus:outline-none text-2xl font-extrabold leading-6 text-center text-slate-800 dark:text-white"
                >
                  Sign up with Email
                </p>
                <form onSubmit={handleSubmit}>
                  <div className="mt-10">
                    <label htmlFor="email" className="sr-only">
                      Email
                    </label>
                    <TextField
                      id="email"
                      name="email"
                      type="email"
                      autoComplete="email"
                      value={email}
                      autoFocus
                      required
                      placeholder="Email"
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div>
                    <label htmlFor="password" className="sr-only">
                      Password
                    </label>
                    <TextField
                      id="password"
                      name="password"
                      type="password"
                      autoComplete="current-password"
                      required
                      value={password}
                      placeholder="Password"
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>
                  <div className="mt-8">
                    <DefaultButton>Sign up</DefaultButton>
                  </div>
                  <p
                    tabIndex="0"
                    className="focus:outline-none text-sm mt-4 font-medium leading-none text-center text-gray-500 dark:text-gray-300"
                  >
                    By clicking signup you will agree to our
                    <Link href="/register">
                      <a
                        rel="noopener"
                        className="hover:text-gray-500 focus:text-gray-500 focus:outline-none focus:underline hover:underline text-sm font-medium leading-none text-gray-800 dark:text-gray-100 cursor-pointer"
                      >
                        {' '}
                        Terms of service
                      </a>
                    </Link>
                    &nbsp;and
                    <Link href="/register">
                      <a
                        rel="noopener"
                        className="hover:text-gray-500 focus:text-gray-500 focus:outline-none focus:underline hover:underline text-sm font-medium leading-none text-gray-800 dark:text-gray-100 cursor-pointer"
                      >
                        {' '}
                        Privacy policy
                      </a>
                    </Link>
                  </p>
                </form>
              </div>
              <Toaster
                position="top-center"
                toastOptions={{
                  // Define default options
                  duration: 5000,
                  style: {
                    background: '#363636',
                    color: '#fff',
                  },
                }}
              />
            </div>
          </div>
        </main>
      </div>
    </React.Fragment>
  );
}
